/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#ifndef _CHANRTS_CHANRTS_H
#define _CHANRTS_CHANRTS_H

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"

#include <vector>
#include <memory>
#include <thread>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <queue>
#include <unordered_map>

// LibTorch integration
#include "LibTorchModel.h"
#include "SpatialInputManager.h"
#include "HierarchicalBuildSystem.h"

namespace chanrts {

// Forward declarations
struct GameState;
struct MLFeatures;
struct MLAction;
struct TrainingData;

/**
 * Represents a single action for a unit
 */
struct UnitAction {
    enum Type {
        NONE = 0,
        MOVE,
        ATTACK,
        BUILD,
        STOP,
        GUARD,
        PATROL
    };
    
    int unitId;
    Type type;
    float x, y, z;          // target position or build location
    int targetUnitId;       // for attack commands
    int buildUnitDefId;     // for build commands
    int priority;           // action priority (0-100)
    
    UnitAction() : unitId(-1), type(NONE), x(0), y(0), z(0), 
                   targetUnitId(-1), buildUnitDefId(-1), priority(0) {}
};

/**
 * Contains all actions from ML inference
 */
struct MLAction {
    std::vector<UnitAction> unitActions;
    float economicPriority[10];  // priorities for different resource allocations
    int strategicState;          // current strategic phase (economy/military/etc)
    int frame;                   // frame this action was generated for
    
    MLAction() : strategicState(0), frame(0) {
        std::fill(economicPriority, economicPriority + 10, 0.0f);
    }
};

/**
 * Comprehensive game state for ML features
 */
struct GameState {
    // Frame info
    int currentFrame;
    float gameProgress;  // 0.0 to 1.0 estimate
    
    // Map info  
    int mapWidth, mapHeight;
    std::vector<float> heightMap;
    std::vector<float> slopeMap;
    std::vector<int> metalMap;
    
    // Visibility maps
    std::vector<int> losMap;
    std::vector<int> radarMap;
    
    // Units (raw coordinates for convolutional networks)
    struct UnitInfo {
        // Core identification
        int id;
        int defId;
        int team;
        bool isEnemy;
        
        // Position and movement (raw coordinates)
        float x, y, z;
        float velX, velY, velZ;  // velocity vector
        float heading;           // facing direction in radians
        float speed, maxSpeed;
        
        // Health and combat
        float health, maxHealth;
        float armor;
        float range, maxRange;
        float firepower;         // damage per second estimate
        int weaponCount;
        bool canAttack;
        
        // Status and behavior
        bool isIdle;
        bool isMoving;
        bool isAttacking;
        bool isBuilding;
        bool isBeingBuilt;
        bool isCloaked;
        bool isStunned;
        bool isParalyzed;
        int commandCount;
        int currentCommandType;  // current Spring command type
        
        // Construction and production
        float buildProgress;
        float buildTime;         // total time to build this unit
        float metalCost;
        float energyCost;
        bool isBuilder;
        bool isFactory;
        std::vector<int> buildQueue; // what this unit is building/queued to build
        
        // Resource production (for economic units)
        float metalMake;         // metal production per second
        float energyMake;        // energy production per second
        float metalUse;          // metal consumption per second
        float energyUse;         // energy consumption per second
        
        // Special abilities and properties
        bool isAmphibious;
        bool canFly;
        bool isTransport;
        int transportCapacity;
        int transportUsed;
        bool isCommander;        // special commander unit
        
        // Experience and veterancy
        float experience;
        int veterancyLevel;
        
        // Timing information
        int lastCommandFrame;    // when this unit last received a command
        int idleTime;           // frames since unit became idle
        int creationFrame;      // when this unit was created
    };
    
    std::vector<UnitInfo> allUnits;
    std::vector<int> friendlyUnitIds;
    std::vector<int> enemyUnitIds;
    
    // Resources
    float metal, energy;
    float metalIncome, energyIncome;
    float metalUsage, energyUsage;
    
    // Strategic info
    int numBases;
    int totalUnitCount;
    int militaryUnitCount;
    int economicUnitCount;
    
    GameState() : currentFrame(0), gameProgress(0.0f), mapWidth(0), mapHeight(0),
                  metal(0), energy(0), metalIncome(0), energyIncome(0),
                  metalUsage(0), energyUsage(0), numBases(0), 
                  totalUnitCount(0), militaryUnitCount(0), economicUnitCount(0) {}
};

/**
 * Training data sample for supervised learning
 */
struct TrainingData {
    GameState state;
    MLAction action;
    float reward;           // outcome reward
    bool gameWon;
    int sampleFrame;
    
    TrainingData() : reward(0.0f), gameWon(false), sampleFrame(0) {}
};

/**
 * Main ChanRTS AI class with ML integration
 */
class CChanRTS {

private:
    // Core Spring AI interface
    springai::OOAICallback* callback;
    int skirmishAIId;
    
    // ML Inference System
    std::unique_ptr<std::thread> inferenceThread;
    std::atomic<bool> shouldStop;
    std::atomic<bool> inferenceReady;
    
    // Thread synchronization
    std::mutex stateMutex;
    std::mutex actionMutex;
    std::condition_variable inferenceCondition;
    
    // Buffered state and actions
    GameState currentState;
    GameState nextState;  // for inference thread
    MLAction currentActions;
    MLAction pendingActions;
    
    // Training data collection
    std::vector<TrainingData> trainingBuffer;
    std::mutex trainingMutex;
    bool collectTrainingData;
    float finalGameReward;
    std::string dataOutputDir;
    bool replayMode;
    int gameId;
    float playerSkill;
    
    // Unit tracking
    std::unordered_map<int, int> unitToLastCommand;
    std::unordered_map<int, int> unitCommandFrames;
    
    // Performance tracking
    int lastInferenceFrame;
    int inferenceCount;
    double totalInferenceTime;
    
    // ML Model Integration
    std::unique_ptr<HierarchicalRTSModel> mlModel;
    std::unique_ptr<SpatialInputManager> spatialInputManager;
    ModelConfig modelConfig;
    bool useMLInference;

public:
    CChanRTS(springai::OOAICallback* callback);
    ~CChanRTS();

    int HandleEvent(int topic, const void* data);

private:
    // Core game loop methods
    void HandleUpdate(int frame);
    void HandleUnitCreated(int unitId, int builderId);
    void HandleUnitDestroyed(int unitId);
    void HandleUnitIdle(int unitId);
    void HandleGameEnd();
    
    // Feature extraction
    void ExtractGameState(GameState& state);
    void ExtractMapFeatures(GameState& state);
    void ExtractUnitFeatures(GameState& state);
    void ExtractEconomicFeatures(GameState& state);
    void ExtractStrategicFeatures(GameState& state);
    GameState::UnitInfo ExtractComprehensiveUnitInfo(springai::Unit* unit, bool isEnemy, int currentFrame);
    
    // ML inference system
    void StartInferenceThread();
    void StopInferenceThread();
    void InferenceThreadLoop();
    void RunMLInference(const GameState& state, MLAction& action);
    
    // ML model management
    bool LoadMLModel();
    void InitializeSpatialInputManager();
    SpatialTensor GameStateToSpatialTensor(const GameState& state);
    MLAction MLOutputToMLAction(const MLOutput& output, int frame);
    
    // Action execution
    void ExecuteActions(const MLAction& actions);
    void ExecuteUnitAction(const UnitAction& action);
    bool IsActionValid(const UnitAction& action);
    
    // Training data management
    void CollectTrainingData(const GameState& state, const MLAction& action);
    void SaveTrainingData();
    void CalculateFinalRewards();
    
    // Data collection modes
    void EnableDataCollection(const std::string& outputDir, bool replayMode = false);
    void DisableDataCollection();
    void SaveTrainingDataBinary();
    void ProcessReplay(const std::string& replayPath, const std::string& outputDir);
    
    // Utility methods
    float NormalizeCoordinate(float coord, float mapSize);
    float CalculateGameProgress();
    int GetUnitDefCategory(int unitDefId);
    bool IsUnitMilitary(int unitDefId);
    bool IsUnitEconomic(int unitDefId);
    
    // Configuration loading
    void CheckDataCollectionConfig();
    void LoadConfigFromFile(const std::string& configPath);
    
}; // class CChanRTS

} // namespace chanrts

#endif // _CHANRTS_CHANRTS_H

