/* This file is part of the Spring engine (GPL v2 or later), see LICENSE.html */

#include "ChanRTS.h"

#include "ExternalAI/Interface/AISEvents.h"
#include "ExternalAI/Interface/AISCommands.h"

// generated by the C++ Wrapper scripts
#include "OOAICallback.h"
#include "Unit.h"
#include "UnitDef.h"
#include "Game.h"
#include "Map.h"
#include "Resource.h"

#include <string>
#include <memory>
#include <chrono>
#include <algorithm>
#include <fstream>
#include <iostream>
#include <cmath>

namespace chanrts {

// Constructor
CChanRTS::CChanRTS(springai::OOAICallback* callback):
    callback(callback),
    skirmishAIId(callback != NULL ? callback->GetSkirmishAIId() : -1),
    shouldStop(false),
    inferenceReady(false),
    collectTrainingData(true),
    finalGameReward(0.0f),
    lastInferenceFrame(0),
    inferenceCount(0),
    totalInferenceTime(0.0),
    useMLInference(false),
    replayMode(false),
    gameId(0),
    playerSkill(20.0f)
{
    // Initialize the inference thread
    StartInferenceThread();
    
    // Initialize game state
    currentState.currentFrame = 0;
    currentActions.frame = 0;
    
    // Initialize ML model and spatial input manager
    LoadMLModel();
    InitializeSpatialInputManager();
    
    // Check for training data collection configuration
    CheckDataCollectionConfig();
    
    // Send initialization message and debug info
    if (callback) {
        const std::unique_ptr<springai::Game> game(callback->GetGame());
        if (game) {
            game->SendTextMessage("/say ChanRTS ML AI initialized with threaded inference!", 0);
            
            // Debug environment variables
            game->SendTextMessage("/say === ENVIRONMENT DEBUG ===", 0);
            
            const char* collectEnv = std::getenv("CHANRTS_COLLECT_DATA");
            const char* outputDirEnv = std::getenv("CHANRTS_OUTPUT_DIR");
            const char* replayModeEnv = std::getenv("CHANRTS_REPLAY_MODE");
            const char* configPathEnv = std::getenv("CHANRTS_CONFIG_PATH");
            const char* playerSkillEnv = std::getenv("CHANRTS_PLAYER_SKILL");
            const char* gameIdEnv = std::getenv("CHANRTS_GAME_ID");
            
            std::string envMsg = "/say CHANRTS_COLLECT_DATA=" + std::string(collectEnv ? collectEnv : "NULL");
            game->SendTextMessage(envMsg.c_str(), 0);
            
            envMsg = "/say CHANRTS_OUTPUT_DIR=" + std::string(outputDirEnv ? outputDirEnv : "NULL");
            game->SendTextMessage(envMsg.c_str(), 0);
            
            envMsg = "/say CHANRTS_REPLAY_MODE=" + std::string(replayModeEnv ? replayModeEnv : "NULL");
            game->SendTextMessage(envMsg.c_str(), 0);
            
            envMsg = "/say CHANRTS_CONFIG_PATH=" + std::string(configPathEnv ? configPathEnv : "NULL");
            game->SendTextMessage(envMsg.c_str(), 0);
            
            envMsg = "/say CHANRTS_PLAYER_SKILL=" + std::string(playerSkillEnv ? playerSkillEnv : "NULL");
            game->SendTextMessage(envMsg.c_str(), 0);
            
            envMsg = "/say CHANRTS_GAME_ID=" + std::string(gameIdEnv ? gameIdEnv : "NULL");
            game->SendTextMessage(envMsg.c_str(), 0);
            
            // Debug final configuration state
            game->SendTextMessage("/say === CONFIG STATE ===", 0);
            std::string debugMsg = "/say collectTrainingData: " + std::string(collectTrainingData ? "TRUE" : "FALSE");
            game->SendTextMessage(debugMsg.c_str(), 0);
            
            std::string outputMsg = "/say dataOutputDir: " + (dataOutputDir.empty() ? "EMPTY" : dataOutputDir);
            game->SendTextMessage(outputMsg.c_str(), 0);
            
            std::string replayMsg = "/say replayMode: " + std::string(replayMode ? "TRUE" : "FALSE");
            game->SendTextMessage(replayMsg.c_str(), 0);
            
            std::string skillMsg = "/say playerSkill: " + std::to_string(playerSkill);
            game->SendTextMessage(skillMsg.c_str(), 0);
            
            std::string gameIdMsg = "/say gameId: " + std::to_string(gameId);
            game->SendTextMessage(gameIdMsg.c_str(), 0);
            
            game->SendTextMessage("/say === END DEBUG ===", 0);
        }
    }
}

// Destructor
CChanRTS::~CChanRTS() {
    StopInferenceThread();
    
    // Save training data before destruction
    if (collectTrainingData && !trainingBuffer.empty()) {
        CalculateFinalRewards();
        
        // Use binary format for replay processing, CSV for regular gameplay
        if (replayMode) {
            SaveTrainingDataBinary();
        } else {
            SaveTrainingData();
        }
    }
}

// Main event handler
int CChanRTS::HandleEvent(int topic, const void* data) {
    try {
        switch (topic) {
            case EVENT_INIT: {
                // AI initialization
                break;
            }
            
            case EVENT_UPDATE: {
                const struct SUpdateEvent* evt = (const struct SUpdateEvent*) data;
                HandleUpdate(evt->frame);
                break;
            }
            
            case EVENT_UNIT_CREATED: {
                const struct SUnitCreatedEvent* evt = (const struct SUnitCreatedEvent*) data;
                HandleUnitCreated(evt->unit, evt->builder);
                break;
            }
            
            case EVENT_UNIT_DESTROYED: {
                const struct SUnitDestroyedEvent* evt = (const struct SUnitDestroyedEvent*) data;
                HandleUnitDestroyed(evt->unit);
                break;
            }
            
            case EVENT_UNIT_IDLE: {
                const struct SUnitIdleEvent* evt = (const struct SUnitIdleEvent*) data;
                HandleUnitIdle(evt->unit);
                break;
            }
            
            case EVENT_RELEASE: {
                HandleGameEnd();
                break;
            }
            
            default: {
                // Handle other events as needed
                break;
            }
        }
    } catch (const std::exception& e) {
        // Log error but don't crash the AI
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = std::string("/say ChanRTS Error: ") + e.what();
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
        return 1; // Signal error but continue
    }
    
    return 0; // Success
}

// Handle game updates (30 FPS)
void CChanRTS::HandleUpdate(int frame) {
    std::lock_guard<std::mutex> lock(stateMutex);
    
    // Update current frame
    currentState.currentFrame = frame;
    
    // Extract comprehensive game state
    ExtractGameState(currentState);
    
    // Signal inference thread if it's ready
    if (inferenceReady.load() && (frame - lastInferenceFrame) > 1) {
        // Copy state for inference thread
        nextState = currentState;
        lastInferenceFrame = frame;
        inferenceCondition.notify_one();
    }
    
    // Execute current actions from previous inference
    if (currentActions.frame > 0 && (frame - currentActions.frame) < 60) { // Execute for up to 2 seconds
        ExecuteActions(currentActions);
    }
    
    // Collect training data at different intervals depending on mode
    int collectionInterval = replayMode ? 30 : 900; // Every 1 second in replay mode, every 30 seconds normally
    if (collectTrainingData && frame % collectionInterval == 0) {
        CollectTrainingData(currentState, currentActions);
        
        // Send debug message about data collection (less frequent in replay mode to avoid spam)
        if (callback && (!replayMode || frame % 900 == 0)) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string msg = "/say DATA COLLECTION: frame " + std::to_string(frame) + 
                                " interval=" + std::to_string(collectionInterval) +
                                " buffer=" + std::to_string(trainingBuffer.size()) + 
                                " replayMode=" + std::string(replayMode ? "TRUE" : "FALSE");
                game->SendTextMessage(msg.c_str(), 0);
            }
        }
    }
    
    // Debug message for first few frames to show collection state
    if (frame <= 90 && frame % 30 == 0) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string debugMsg = "/say Frame " + std::to_string(frame) + 
                                     " collectTrainingData=" + std::string(collectTrainingData ? "TRUE" : "FALSE") +
                                     " interval=" + std::to_string(collectionInterval);
                game->SendTextMessage(debugMsg.c_str(), 0);
            }
        }
    }
}

// Handle unit creation
void CChanRTS::HandleUnitCreated(int unitId, int builderId) {
    // Track new units
    unitCommandFrames[unitId] = currentState.currentFrame;
    unitToLastCommand[unitId] = 0; // No command yet
}

// Handle unit destruction
void CChanRTS::HandleUnitDestroyed(int unitId) {
    // Clean up tracking data
    unitCommandFrames.erase(unitId);
    unitToLastCommand.erase(unitId);
}

// Handle idle units
void CChanRTS::HandleUnitIdle(int unitId) {
    // Mark unit as available for new commands
    unitToLastCommand[unitId] = 0;
}

// Handle game end
void CChanRTS::HandleGameEnd() {
    if (collectTrainingData && !trainingBuffer.empty()) {
        CalculateFinalRewards();
        SaveTrainingData();
    }
}

// Start the inference thread
void CChanRTS::StartInferenceThread() {
    shouldStop = false;
    inferenceReady = true;
    inferenceThread = std::make_unique<std::thread>(&CChanRTS::InferenceThreadLoop, this);
}

// Stop the inference thread
void CChanRTS::StopInferenceThread() {
    shouldStop = true;
    inferenceCondition.notify_all();
    
    if (inferenceThread && inferenceThread->joinable()) {
        inferenceThread->join();
    }
}

// Main inference thread loop
void CChanRTS::InferenceThreadLoop() {
    GameState localState;
    MLAction localAction;
    
    while (!shouldStop.load()) {
        // Wait for new state data
        std::unique_lock<std::mutex> lock(stateMutex);
        inferenceCondition.wait(lock, [this, &localState] { 
            return shouldStop.load() || nextState.currentFrame > localState.currentFrame; 
        });
        
        if (shouldStop.load()) break;
        
        // Copy state for processing
        localState = nextState;
        lock.unlock();
        
        // Run ML inference
        auto startTime = std::chrono::high_resolution_clock::now();
        
        RunMLInference(localState, localAction);
        
        auto endTime = std::chrono::high_resolution_clock::now();
        auto duration = std::chrono::duration_cast<std::chrono::microseconds>(endTime - startTime);
        
        // Update performance metrics
        inferenceCount++;
        totalInferenceTime += duration.count() / 1000.0; // Convert to milliseconds
        
        // Update current actions with thread safety
        {
            std::lock_guard<std::mutex> actionLock(actionMutex);
            pendingActions = localAction;
            pendingActions.frame = localState.currentFrame;
            
            // Swap pending actions to current if they're newer
            if (pendingActions.frame > currentActions.frame) {
                currentActions = pendingActions;
            }
        }
    }
}

// ML inference placeholder - replace with actual model
void CChanRTS::RunMLInference(const GameState& state, MLAction& action) {
    action.unitActions.clear();
    action.strategicState = 1; // Default to economic phase
    action.frame = state.currentFrame;
    
    // Early exit if ML inference is not available or enabled
    if (!useMLInference || !mlModel || !spatialInputManager) {
        // Fallback to simple rule-based behavior
        printf("ChanRTS: Using rule-based fallback (ML not available)\n");
        
        // Simple rule: idle units should move randomly or build
        for (const auto& unitInfo : state.allUnits) {
            if (!unitInfo.isEnemy && unitInfo.isIdle) {
                UnitAction unitAction;
                unitAction.unitId = unitInfo.id;
                
                // Simple strategy: builders build, others move randomly
                if (IsUnitEconomic(unitInfo.defId)) {
                    unitAction.type = UnitAction::BUILD;
                    // Find a build location (simplified)
                    unitAction.x = unitInfo.x + (rand() % 200 - 100);
                    unitAction.y = unitInfo.y + (rand() % 200 - 100);
                    unitAction.z = unitInfo.z;
                    unitAction.buildUnitDefId = 1; // Placeholder
                } else {
                    unitAction.type = UnitAction::MOVE;
                    unitAction.x = rand() % state.mapWidth;
                    unitAction.y = rand() % state.mapHeight;
                    unitAction.z = 0;
                }
                
                unitAction.priority = 50;
                action.unitActions.push_back(unitAction);
            }
        }
        return;
    }
    
    try {
        printf("ChanRTS: Running ML inference for frame %d\n", state.currentFrame);
        
        // Convert game state to spatial tensor
        SpatialTensor inputTensor = GameStateToSpatialTensor(state);
        printf("ChanRTS: Generated spatial tensor %dx%dx%d\n", inputTensor.width, inputTensor.height, inputTensor.channels);
        
        // Run inference through the neural network
        MLOutput mlOutput = mlModel->Inference(inputTensor);
        printf("ChanRTS: ML inference completed\n");
        
        // Convert ML output to game actions
        action = MLOutputToMLAction(mlOutput, state.currentFrame);
        printf("ChanRTS: Generated %d unit actions from ML output\n", (int)action.unitActions.size());
        
    } catch (const std::exception& e) {
        printf("ChanRTS: ML inference failed with error: %s\n", e.what());
        printf("ChanRTS: Falling back to rule-based behavior\n");
        
        // Fallback to rule-based behavior on ML failure
        for (const auto& unitInfo : state.allUnits) {
            if (!unitInfo.isEnemy && unitInfo.isIdle) {
                UnitAction unitAction;
                unitAction.unitId = unitInfo.id;
                unitAction.type = UnitAction::MOVE;
                unitAction.x = rand() % state.mapWidth;
                unitAction.y = rand() % state.mapHeight;
                unitAction.z = 0;
                unitAction.priority = 50;
                action.unitActions.push_back(unitAction);
            }
        }
    }
}

// Execute ML actions
void CChanRTS::ExecuteActions(const MLAction& actions) {
    for (const auto& unitAction : actions.unitActions) {
        if (IsActionValid(unitAction)) {
            ExecuteUnitAction(unitAction);
        }
    }
}

// Execute individual unit action
void CChanRTS::ExecuteUnitAction(const UnitAction& action) {
    if (!callback) return;
    
    // Get unit pointer
    std::vector<springai::Unit*> friendlyUnits = callback->GetFriendlyUnits();
    springai::Unit* targetUnit = nullptr;
    
    for (springai::Unit* unit : friendlyUnits) {
        if (unit->GetUnitId() == action.unitId) {
            targetUnit = unit;
            break;
        }
    }
    
    if (!targetUnit) {
        // Clean up memory
        for (springai::Unit* unit : friendlyUnits) {
            delete unit;
        }
        return;
    }
    
    // Execute action based on type
    try {
        switch (action.type) {
            case UnitAction::MOVE: {
                springai::AIFloat3 pos;
                pos.x = action.x;
                pos.y = action.y;
                pos.z = action.z;
                targetUnit->MoveTo(pos);
                break;
            }
            
            case UnitAction::ATTACK: {
                // Find target unit (simplified)
                std::vector<springai::Unit*> enemyUnits = callback->GetEnemyUnits();
                for (springai::Unit* enemy : enemyUnits) {
                    if (enemy->GetUnitId() == action.targetUnitId) {
                        targetUnit->Attack(enemy);
                        break;
                    }
                }
                for (springai::Unit* enemy : enemyUnits) {
                    delete enemy;
                }
                break;
            }
            
            case UnitAction::BUILD: {
                // Simplified build command
                springai::AIFloat3 pos;
                pos.x = action.x;
                pos.y = action.y;
                pos.z = action.z;
                
                // Get unit def (simplified - would need proper unit def lookup)
                std::vector<springai::UnitDef*> unitDefs = callback->GetUnitDefs();
                if (!unitDefs.empty() && action.buildUnitDefId < unitDefs.size()) {
                    targetUnit->Build(unitDefs[action.buildUnitDefId], pos, 0);
                }
                for (springai::UnitDef* unitDef : unitDefs) {
                    delete unitDef;
                }
                break;
            }
            
            case UnitAction::STOP: {
                targetUnit->Stop();
                break;
            }
            
            default: {
                // Do nothing for unknown actions
                break;
            }
        }
        
        // Update command tracking
        unitToLastCommand[action.unitId] = currentState.currentFrame;
        
    } catch (const std::exception& e) {
        // Log error but continue
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = std::string("/say Action error: ") + e.what();
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
    
    // Clean up memory
    for (springai::Unit* unit : friendlyUnits) {
        delete unit;
    }
}

// Validate action before execution
bool CChanRTS::IsActionValid(const UnitAction& action) {
    // Basic validation
    if (action.unitId < 0 || action.type == UnitAction::NONE) {
        return false;
    }
    
    // Check if unit was commanded recently (avoid spam)
    auto it = unitToLastCommand.find(action.unitId);
    if (it != unitToLastCommand.end()) {
        int framesSinceLastCommand = currentState.currentFrame - it->second;
        if (framesSinceLastCommand < 5) { // Wait at least 5 frames between commands
            return false;
        }
    }
    
    // Check coordinate bounds (raw map coordinates)
    if (action.type == UnitAction::MOVE || action.type == UnitAction::BUILD) {
        if (action.x < 0 || action.x > currentState.mapWidth || action.z < 0 || action.z > currentState.mapHeight) {
            return false;
        }
    }
    
    return true;
}

// Utility functions
float CChanRTS::NormalizeCoordinate(float coord, float mapSize) {
    return std::max(0.0f, std::min(1.0f, coord / mapSize));
}

float CChanRTS::CalculateGameProgress() {
    // Simple progress estimation based on frame count
    // Typical RTS games last 1800-3600 frames (1-2 minutes at 30 FPS)
    float estimatedGameLength = 3600.0f;
    return std::min(1.0f, currentState.currentFrame / estimatedGameLength);
}

int CChanRTS::GetUnitDefCategory(int unitDefId) {
    // Placeholder - would need proper unit definition analysis
    return 0;
}

bool CChanRTS::IsUnitMilitary(int unitDefId) {
    // Placeholder - would need proper unit definition analysis
    return unitDefId % 2 == 0; // Simple placeholder logic
}

bool CChanRTS::IsUnitEconomic(int unitDefId) {
    // Placeholder - would need proper unit definition analysis
    return unitDefId % 2 == 1; // Simple placeholder logic
}

// Main feature extraction method
void CChanRTS::ExtractGameState(GameState& state) {
    if (!callback) return;
    
    ExtractMapFeatures(state);
    ExtractUnitFeatures(state);
    ExtractEconomicFeatures(state);
    ExtractStrategicFeatures(state);
    
    state.gameProgress = CalculateGameProgress();
}

// Extract map and terrain features
void CChanRTS::ExtractMapFeatures(GameState& state) {
    try {
        const std::unique_ptr<springai::Map> map(callback->GetMap());
        if (!map) return;
        
        state.mapWidth = map->GetWidth();
        state.mapHeight = map->GetHeight();
        
        // Get terrain data
        state.heightMap = map->GetHeightMap();
        state.slopeMap = map->GetSlopeMap();
        
        // Get visibility maps
        state.losMap = map->GetLosMap();
        state.radarMap = map->GetRadarMap();
        
        // Get metal map (resource locations) - not available in this Spring version
        // TODO: Find alternative way to get resource locations
        state.metalMap.clear();
        
    } catch (const std::exception& e) {
        // Log error but continue
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = std::string("/say Map extraction error: ") + e.what();
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Extract comprehensive unit features
void CChanRTS::ExtractUnitFeatures(GameState& state) {
    try {
        state.allUnits.clear();
        state.friendlyUnitIds.clear();
        state.enemyUnitIds.clear();
        
        // Get friendly units
        std::vector<springai::Unit*> friendlyUnits = callback->GetFriendlyUnits();
        for (springai::Unit* unit : friendlyUnits) {
            GameState::UnitInfo unitInfo = ExtractComprehensiveUnitInfo(unit, false, state.currentFrame);
            state.allUnits.push_back(unitInfo);
            state.friendlyUnitIds.push_back(unitInfo.id);
        }
        
        // Clean up friendly units
        for (springai::Unit* unit : friendlyUnits) {
            delete unit;
        }
        
        // Get enemy units
        std::vector<springai::Unit*> enemyUnits = callback->GetEnemyUnits();
        for (springai::Unit* unit : enemyUnits) {
            GameState::UnitInfo unitInfo = ExtractComprehensiveUnitInfo(unit, true, state.currentFrame);
            state.allUnits.push_back(unitInfo);
            state.enemyUnitIds.push_back(unitInfo.id);
        }
        
        // Clean up enemy units
        for (springai::Unit* unit : enemyUnits) {
            delete unit;
        }
        
    } catch (const std::exception& e) {
        // Log error but continue
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = std::string("/say Unit extraction error: ") + e.what();
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Extract economic and resource features
void CChanRTS::ExtractEconomicFeatures(GameState& state) {
    // Reset resource values - simplified for now
    // TODO: Find correct API methods for resource extraction
    state.metal = 0;
    state.energy = 0;
    state.metalIncome = 0;
    state.energyIncome = 0;
    state.metalUsage = 0;
    state.energyUsage = 0;
    
    try {
        // Basic resource detection - resources exist but specific values need different API
        std::vector<springai::Resource*> resources = callback->GetResources();
        
        // At least we can detect resource types
        for (springai::Resource* resource : resources) {
            std::string resourceName = resource->GetName();
            
            // Placeholder values - would need correct API methods
            if (resourceName == "Metal") {
                state.metal = 100.0f;  // Placeholder
                state.metalIncome = 5.0f;
            }
            else if (resourceName == "Energy") {
                state.energy = 100.0f;  // Placeholder
                state.energyIncome = 10.0f;
            }
        }
        
        // Clean up resources
        for (springai::Resource* resource : resources) {
            delete resource;
        }
        
    } catch (const std::exception& e) {
        // Log error but continue - resource extraction might not work on all maps
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = std::string("/say Economic extraction error: ") + e.what();
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Extract strategic and high-level features
void CChanRTS::ExtractStrategicFeatures(GameState& state) {
    // Calculate unit counts by category
    state.totalUnitCount = 0;
    state.militaryUnitCount = 0;
    state.economicUnitCount = 0;
    state.numBases = 0;
    
    for (const auto& unitInfo : state.allUnits) {
        if (!unitInfo.isEnemy) {
            state.totalUnitCount++;
            
            if (IsUnitMilitary(unitInfo.defId)) {
                state.militaryUnitCount++;
            }
            else if (IsUnitEconomic(unitInfo.defId)) {
                state.economicUnitCount++;
                
                // Rough base counting (buildings that produce resources)
                if (unitInfo.buildProgress > 0.9f) {
                    state.numBases++;
                }
            }
        }
    }
}

// Training data collection
void CChanRTS::CollectTrainingData(const GameState& state, const MLAction& action) {
    if (!collectTrainingData) return;
    
    std::lock_guard<std::mutex> lock(trainingMutex);
    
    TrainingData sample;
    sample.state = state;
    sample.action = action;
    sample.sampleFrame = state.currentFrame;
    sample.reward = 0.0f; // Will be calculated later
    sample.gameWon = false; // Unknown until game ends
    
    trainingBuffer.push_back(sample);
    
    // Limit buffer size to prevent memory issues
    if (trainingBuffer.size() > 10000) {
        trainingBuffer.erase(trainingBuffer.begin(), trainingBuffer.begin() + 1000);
    }
}

// Calculate final rewards based on game outcome
void CChanRTS::CalculateFinalRewards() {
    if (trainingBuffer.empty()) return;
    
    std::lock_guard<std::mutex> lock(trainingMutex);
    
    // Simple reward calculation based on game progress and outcome
    // This is a placeholder - you'd want more sophisticated reward shaping
    
    bool gameWon = (finalGameReward > 0);
    
    for (auto& sample : trainingBuffer) {
        sample.gameWon = gameWon;
        
        // Time-discounted reward (earlier actions have less impact)
        float timeFactor = 1.0f - (sample.sampleFrame / float(currentState.currentFrame));
        
        // Base reward from game outcome
        float baseReward = gameWon ? 1.0f : -1.0f;
        
        // Add intermediate rewards for good behavior
        float intermediateReward = 0.0f;
        
        // Reward for economic growth
        if (sample.state.metalIncome > 0 || sample.state.energyIncome > 0) {
            intermediateReward += 0.1f;
        }
        
        // Reward for unit production
        if (sample.state.totalUnitCount > 1) {
            intermediateReward += 0.1f;
        }
        
        // Penalty for resource waste
        if (sample.state.metal > 1000 || sample.state.energy > 1000) {
            intermediateReward -= 0.05f;
        }
        
        sample.reward = (baseReward * timeFactor) + intermediateReward;
    }
}

// Save training data to file
void CChanRTS::SaveTrainingData() {
    // Debug message
    if (callback) {
        const std::unique_ptr<springai::Game> game(callback->GetGame());
        if (game) {
            std::string msg = "/say Attempting to save " + std::to_string(trainingBuffer.size()) + " training samples";
            game->SendTextMessage(msg.c_str(), 0);
        }
    }
    
    if (trainingBuffer.empty()) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                game->SendTextMessage("/say No training data to save (buffer empty)", 0);
            }
        }
        return;
    }
    
    std::lock_guard<std::mutex> lock(trainingMutex);
    
    try {
        // Create filename with timestamp
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);
        
        // Try multiple directories for saving training data
        std::string filename;
        std::ofstream file;
        bool saved_successfully = false;
        
        // Try to save to the configured output directory first
        if (!dataOutputDir.empty()) {
            // Ensure the output directory exists
            std::string output_dir = dataOutputDir;
            if (output_dir.back() == '/') {
                output_dir.pop_back(); // Remove trailing slash
            }
            
            // Create directory if it doesn't exist
            std::string mkdir_cmd = "mkdir -p \"" + output_dir + "\"";
            system(mkdir_cmd.c_str());
            
            filename = output_dir + "/chanrts_training_data_" + std::to_string(time_t) + ".csv";
            file.open(filename);
            if (file.is_open()) {
                saved_successfully = true;
            } else {
                // Fallback to /tmp if configured directory fails
                if (callback) {
                    const std::unique_ptr<springai::Game> game(callback->GetGame());
                    if (game) {
                        std::string msg = "/say Failed to write to configured output dir, trying /tmp/";
                        game->SendTextMessage(msg.c_str(), 0);
                    }
                }
            }
        }
        
        // Try /tmp directory if not already successful and no output_dir configured
        if (!saved_successfully) {
            filename = "/tmp/chanrts_training_data_" + std::to_string(time_t) + ".csv";
            file.open(filename);
            if (file.is_open()) {
                saved_successfully = true;
            }
        }
        
        // Try default directory if still not successful
        if (!saved_successfully && dataOutputDir.empty()) {
            filename = "./chanrts_training_data_" + std::to_string(time_t) + ".csv";
            file.open(filename);
            if (file.is_open()) {
                saved_successfully = true;
            }
        }

        if (saved_successfully) {
            // Write comprehensive CSV header
            file << "frame,game_progress,map_width,map_height,total_units,military_units,"
                 << "economic_units,metal,energy,metal_income,energy_income,"
                 << "action_count,strategic_state,reward,game_won,unit_count,"
                 << "unit_data\n";
            
            // Write training samples with comprehensive unit data
            for (const auto& sample : trainingBuffer) {
                file << sample.sampleFrame << ","
                     << sample.state.gameProgress << ","
                     << sample.state.mapWidth << ","
                     << sample.state.mapHeight << ","
                     << sample.state.totalUnitCount << ","
                     << sample.state.militaryUnitCount << ","
                     << sample.state.economicUnitCount << ","
                     << sample.state.metal << ","
                     << sample.state.energy << ","
                     << sample.state.metalIncome << ","
                     << sample.state.energyIncome << ","
                     << sample.action.unitActions.size() << ","
                     << sample.action.strategicState << ","
                     << sample.reward << ","
                     << (sample.gameWon ? 1 : 0) << ","
                     << sample.state.allUnits.size() << ","
                     << "\"[";
                
                // Write detailed unit information as JSON-like array
                for (size_t i = 0; i < sample.state.allUnits.size(); ++i) {
                    const auto& unit = sample.state.allUnits[i];
                    if (i > 0) file << ",";
                    file << "{"
                         << "id:" << unit.id
                         << ",defId:" << unit.defId
                         << ",team:" << unit.team
                         << ",isEnemy:" << (unit.isEnemy ? 1 : 0)
                         << ",x:" << unit.x
                         << ",y:" << unit.y
                         << ",z:" << unit.z
                         << ",velX:" << unit.velX
                         << ",velY:" << unit.velY
                         << ",velZ:" << unit.velZ
                         << ",speed:" << unit.speed
                         << ",maxSpeed:" << unit.maxSpeed
                         << ",heading:" << unit.heading
                         << ",health:" << unit.health
                         << ",maxHealth:" << unit.maxHealth
                         << ",armor:" << unit.armor
                         << ",range:" << unit.maxRange
                         << ",firepower:" << unit.firepower
                         << ",weaponCount:" << unit.weaponCount
                         << ",canAttack:" << (unit.canAttack ? 1 : 0)
                         << ",isIdle:" << (unit.isIdle ? 1 : 0)
                         << ",isMoving:" << (unit.isMoving ? 1 : 0)
                         << ",isAttacking:" << (unit.isAttacking ? 1 : 0)
                         << ",isBuilding:" << (unit.isBuilding ? 1 : 0)
                         << ",isBeingBuilt:" << (unit.isBeingBuilt ? 1 : 0)
                         << ",isCloaked:" << (unit.isCloaked ? 1 : 0)
                         << ",isStunned:" << (unit.isStunned ? 1 : 0)
                         << ",commandCount:" << unit.commandCount
                         << ",currentCommandType:" << unit.currentCommandType
                         << ",buildProgress:" << unit.buildProgress
                         << ",buildTime:" << unit.buildTime
                         << ",metalCost:" << unit.metalCost
                         << ",energyCost:" << unit.energyCost
                         << ",isBuilder:" << (unit.isBuilder ? 1 : 0)
                         << ",isFactory:" << (unit.isFactory ? 1 : 0)
                         << ",metalMake:" << unit.metalMake
                         << ",energyMake:" << unit.energyMake
                         << ",metalUse:" << unit.metalUse
                         << ",energyUse:" << unit.energyUse
                         << ",isAmphibious:" << (unit.isAmphibious ? 1 : 0)
                         << ",canFly:" << (unit.canFly ? 1 : 0)
                         << ",isTransport:" << (unit.isTransport ? 1 : 0)
                         << ",transportCapacity:" << unit.transportCapacity
                         << ",transportUsed:" << unit.transportUsed
                         << ",isCommander:" << (unit.isCommander ? 1 : 0)
                         << ",experience:" << unit.experience
                         << ",veterancyLevel:" << unit.veterancyLevel
                         << ",lastCommandFrame:" << unit.lastCommandFrame
                         << ",idleTime:" << unit.idleTime
                         << ",creationFrame:" << unit.creationFrame
                         << ",buildQueueSize:" << unit.buildQueue.size()
                         << "}";
                }
                file << "]\"\n";
            }
            
            file.close();
            
            // Send confirmation message
            if (callback) {
                const std::unique_ptr<springai::Game> game(callback->GetGame());
                if (game) {
                    std::string msg = "/say Training data saved: " + filename + 
                                    " (" + std::to_string(trainingBuffer.size()) + " samples)";
                    game->SendTextMessage(msg.c_str(), 0);
                }
            }
        } else {
            // Failed to save anywhere
            if (callback) {
                const std::unique_ptr<springai::Game> game(callback->GetGame());
                if (game) {
                    std::string errorMsg = "/say ERROR: Failed to save training data to any directory!";
                    game->SendTextMessage(errorMsg.c_str(), 0);
                }
            }
        }
        
    } catch (const std::exception& e) {
        // Log error
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = std::string("/say Training data save error: ") + e.what();
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Extract comprehensive unit information
GameState::UnitInfo CChanRTS::ExtractComprehensiveUnitInfo(springai::Unit* unit, bool isEnemy, int currentFrame) {
    GameState::UnitInfo unitInfo;
    
    // Core identification
    unitInfo.id = unit->GetUnitId();
    unitInfo.team = unit->GetTeam();
    unitInfo.isEnemy = isEnemy;
    
    // Position and movement (raw coordinates)
    springai::AIFloat3 pos = unit->GetPos();
    unitInfo.x = pos.x;
    unitInfo.y = pos.y;
    unitInfo.z = pos.z;
    
    springai::AIFloat3 vel = unit->GetVel();
    unitInfo.velX = vel.x;
    unitInfo.velY = vel.y;
    unitInfo.velZ = vel.z;
    unitInfo.speed = vel.Length();
    unitInfo.maxSpeed = unit->GetMaxSpeed();
    
    // Health and combat
    unitInfo.health = unit->GetHealth();
    unitInfo.maxHealth = unit->GetMaxHealth();
    unitInfo.maxRange = unit->GetMaxRange();
    
    // Unit definition info for detailed properties
    const std::unique_ptr<springai::UnitDef> unitDef(unit->GetDef());
    if (unitDef) {
        unitInfo.defId = unitDef->GetUnitDefId();
        unitInfo.armor = unitDef->GetArmorType();
        // Get resource costs using correct Spring API
        auto resources = callback->GetResources();
        for (springai::Resource* res : resources) {
            std::string name = res->GetName();
            if (name == "Metal") {
                unitInfo.metalCost = unitDef->GetCost(res);
            } else if (name == "Energy") {
                unitInfo.energyCost = unitDef->GetCost(res);
            }
            delete res;
        }
        unitInfo.buildTime = unitDef->GetBuildTime();
        unitInfo.isBuilder = unitDef->IsBuilder();
        unitInfo.isAmphibious = unitDef->IsAbleToMove() && unitDef->GetMinWaterDepth() >= 0;
        unitInfo.canFly = unitDef->IsAbleToFly();
        unitInfo.transportCapacity = unitDef->GetTransportCapacity();
        // Determine commander status by name pattern (Spring API doesn't have IsCommander())
        std::string unitName = unitDef->GetName();
        unitInfo.isCommander = (unitName.find("com") != std::string::npos && 
                               (unitName.find("arm") == 0 || unitName.find("cor") == 0 || unitName.find("leg") == 0));
        
        // Extract weapon information (simplified - actual weapon API would need proper headers)
        // Spring API weapon access is complex, using simplified approach for now
        unitInfo.weaponCount = 0;  // Placeholder
        unitInfo.canAttack = unitInfo.maxRange > 0;  // Approximation
        unitInfo.firepower = unitInfo.maxRange > 0 ? 10.0f : 0.0f;  // Placeholder value
        
        // Resource production/consumption using correct Spring API
        auto resources2 = callback->GetResources();
        springai::Resource* metalRes = nullptr;
        springai::Resource* energyRes = nullptr;
        for (springai::Resource* res : resources2) {
            std::string name = res->GetName();
            if (name == "Metal") {
                metalRes = res;
                unitInfo.metalMake = unitDef->GetResourceMake(res);
                unitInfo.metalUse = unitDef->GetUpkeep(res);
            } else if (name == "Energy") {
                energyRes = res;
                unitInfo.energyMake = unitDef->GetResourceMake(res);
                unitInfo.energyUse = unitDef->GetUpkeep(res);
            }
            delete res;
        }
        
        unitInfo.isFactory = unitDef->GetBuildOptions().size() > 0;
    } else {
        // Default values if unitDef is not available
        unitInfo.defId = -1;
        unitInfo.armor = 0.0f;
        unitInfo.metalCost = 0.0f;
        unitInfo.energyCost = 0.0f;
        unitInfo.buildTime = 0.0f;
        unitInfo.isBuilder = false;
        unitInfo.isAmphibious = false;
        unitInfo.canFly = false;
        unitInfo.transportCapacity = 0;
        unitInfo.isCommander = false;
        unitInfo.weaponCount = 0;
        unitInfo.canAttack = false;
        unitInfo.firepower = 0.0f;
        unitInfo.metalMake = 0.0f;
        unitInfo.energyMake = 0.0f;
        unitInfo.metalUse = 0.0f;
        unitInfo.energyUse = 0.0f;
        unitInfo.isFactory = false;
    }
    
    // Status and behavior
    if (!isEnemy) {
        // For friendly units, use simplified status detection (avoid incomplete Command type)
        unitInfo.commandCount = 0;  // Placeholder - would need proper Command API headers
        unitInfo.currentCommandType = -1;  // Placeholder
        
        // Build status and progress
        unitInfo.buildProgress = unit->GetBuildProgress();
        unitInfo.isBeingBuilt = (unitInfo.buildProgress < 1.0f);
        
        // Simplified status detection using available data
        unitInfo.isIdle = (unitInfo.speed < 0.1f);
        unitInfo.isMoving = (unitInfo.speed > 0.1f);
        unitInfo.isBuilding = unitInfo.isBuilder && !unitInfo.isIdle;
        unitInfo.isAttacking = unitInfo.canAttack && !unitInfo.isIdle;
        
        // Build queue information (simplified - would need proper Command API)
        unitInfo.buildQueue.clear();
        
        // Experience and veterancy (simplified)
        unitInfo.experience = unit->GetExperience();
        
        // Timing information
        auto it = unitToLastCommand.find(unitInfo.id);
        if (it != unitToLastCommand.end()) {
            unitInfo.lastCommandFrame = it->second;
            unitInfo.idleTime = unitInfo.isIdle ? (currentFrame - it->second) : 0;
        } else {
            unitInfo.lastCommandFrame = 0;
            unitInfo.idleTime = 0;
        }
        
        auto creationIt = unitCommandFrames.find(unitInfo.id);
        unitInfo.creationFrame = (creationIt != unitCommandFrames.end()) ? creationIt->second : 0;
        
    } else {
        // For enemy units, we have limited information
        unitInfo.commandCount = 0;
        unitInfo.isIdle = false;
        unitInfo.currentCommandType = -1;
        unitInfo.buildProgress = 0.0f;
        unitInfo.isBeingBuilt = false;
        unitInfo.isMoving = (unitInfo.speed > 0.1f);
        unitInfo.isBuilding = false;
        unitInfo.isAttacking = false;
        unitInfo.buildQueue.clear();
        unitInfo.experience = 0.0f;
        unitInfo.lastCommandFrame = 0;
        unitInfo.idleTime = 0;
        unitInfo.creationFrame = 0;
    }
    
    // Advanced status detection (available for both friendly and enemy)
    unitInfo.isCloaked = unit->IsCloaked();
    unitInfo.isStunned = unit->IsParalyzed(); // Spring uses paralyzed for stunned
    unitInfo.isParalyzed = unit->IsParalyzed();
    
    // Transport information
    unitInfo.transportUsed = 0; // Would need additional API to get transported units
    unitInfo.isTransport = (unitInfo.transportCapacity > 0);
    
    // Veterancy calculation based on experience
    unitInfo.veterancyLevel = 0;
    if (unitInfo.experience > 0.0f) {
        unitInfo.veterancyLevel = static_cast<int>(unitInfo.experience / 10.0f); // Rough estimate
    }
    
    // Calculate heading from velocity if moving
    if (unitInfo.speed > 0.1f) {
        unitInfo.heading = atan2(unitInfo.velZ, unitInfo.velX);
    } else {
        unitInfo.heading = 0.0f;
    }
    
    return unitInfo;
}

// Load ML model from the AI data directory
bool CChanRTS::LoadMLModel() {
    try {
        // Model path is in the AI's data directory (gets installed with build_all_ais.sh)
        // Use a simple fallback path for model loading  
        std::string dataDir = ".";
        if (dataDir.empty()) {
            // Fallback to current directory
            dataDir = ".";
        }
        
        std::string modelPath = dataDir + "/chanrts_model.pth";
        std::string configPath = dataDir + "/model_config.json";
        
        // Send debug message about model loading
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string msg = "/say Looking for model at: " + modelPath;
                game->SendTextMessage(msg.c_str(), 0);
            }
        }
        
        // Check if model files exist
        std::ifstream modelFile(modelPath);
        std::ifstream configFile(configPath);
        
        if (!modelFile.good()) {
            if (callback) {
                const std::unique_ptr<springai::Game> game(callback->GetGame());
                if (game) {
                    game->SendTextMessage("/say Model file not found - using rule-based AI", 0);
                }
            }
            useMLInference = false;
            return false;
        }
        
        // Load model configuration
        if (configFile.good()) {
            modelConfig = ModelConfig::FromFile(configPath);
        } else {
            // Use default configuration
            modelConfig = ModelConfig();
            if (callback) {
                const std::unique_ptr<springai::Game> game(callback->GetGame());
                if (game) {
                    game->SendTextMessage("/say Using default model config", 0);
                }
            }
        }
        
        // Create and load the model
        mlModel = std::make_unique<HierarchicalRTSModel>(modelConfig);
        mlModel->LoadFromFile(modelPath);
        mlModel->SetDevice(modelConfig.device);
        mlModel->SetEvalMode();
        
        useMLInference = true;
        
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string msg = "/say ML model loaded successfully (" + modelConfig.backboneType + ")";
                game->SendTextMessage(msg.c_str(), 0);
            }
        }
        
        return true;
        
    } catch (const std::exception& e) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = "/say Model loading failed: " + std::string(e.what());
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
        useMLInference = false;
        return false;
    }
}

// Initialize spatial input manager
void CChanRTS::InitializeSpatialInputManager() {
    if (!callback) return;
    
    try {
        spatialInputManager = std::make_unique<SpatialInputManager>(callback);
        
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                game->SendTextMessage("/say Spatial input manager initialized", 0);
            }
        }
        
    } catch (const std::exception& e) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = "/say Spatial input manager init failed: " + std::string(e.what());
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Convert GameState to spatial tensor for ML input
SpatialTensor CChanRTS::GameStateToSpatialTensor(const GameState& state) {
    if (!spatialInputManager) {
        // Return empty tensor if spatial input manager not available
        SpatialTensor tensor;
        tensor.width = 512;
        tensor.height = 512;
        tensor.channels = 968;
        tensor.data.resize(tensor.channels * tensor.width * tensor.height, 0.0f);
        return tensor;
    }
    
    // Update the spatial input manager with current game state
    spatialInputManager->UpdateInputTensor(state);
    
    // Get the processed tensor for inference
    return spatialInputManager->GetInputTensorForInference();
}

// Convert ML model output to MLAction
MLAction CChanRTS::MLOutputToMLAction(const MLOutput& output, int frame) {
    MLAction action;
    action.frame = frame;
    action.unitActions.clear();
    
    // Convert unit selection output to unit actions
    if (!output.unitSelectionScores.empty()) {
        // Find top-k selected units and generate actions for them
        // This is simplified - you'd want more sophisticated action generation
        
        for (size_t i = 0; i < output.unitSelectionScores.size() && i < 100; ++i) {
            if (output.unitSelectionScores[i] > 0.5f) { // Threshold for unit selection
                UnitAction unitAction;
                unitAction.unitId = static_cast<int>(i);
                unitAction.type = UnitAction::MOVE; // Simplified
                unitAction.priority = static_cast<int>(output.unitSelectionScores[i] * 100);
                
                // Use spatial command outputs to determine target locations
                // This is highly simplified - real implementation would be more complex
                if (!output.spatialCommands.empty()) {
                    unitAction.x = output.spatialCommands[0][0] * currentState.mapWidth;
                    unitAction.y = output.spatialCommands[0][1] * currentState.mapHeight;
                    unitAction.z = 0;
                }
                
                action.unitActions.push_back(unitAction);
            }
        }
    }
    
    // Set strategic state from global parameters
    if (!output.globalParams.empty()) {
        action.strategicState = static_cast<int>(output.globalParams[0] * 10); // Scale to 0-10
        
        // Copy economic priorities
        for (int i = 0; i < 10 && i < output.globalParams.size(); ++i) {
            action.economicPriority[i] = output.globalParams[i];
        }
    }
    
    return action;
}

// Training data collection mode control
void CChanRTS::EnableDataCollection(const std::string& outputDir, bool replayMode) {
    std::lock_guard<std::mutex> lock(trainingMutex);
    collectTrainingData = true;
    dataOutputDir = outputDir;
    this->replayMode = replayMode;
    
    // Clear existing buffer
    trainingBuffer.clear();
    
    if (callback) {
        const std::unique_ptr<springai::Game> game(callback->GetGame());
        if (game) {
            std::string msg = "/say Data collection ENABLED - output: " + outputDir;
            game->SendTextMessage(msg.c_str(), 0);
            if (replayMode) {
                game->SendTextMessage("/say Replay mode: ON (enhanced collection)", 0);
            }
        }
    }
}

void CChanRTS::DisableDataCollection() {
    std::lock_guard<std::mutex> lock(trainingMutex);
    collectTrainingData = false;
    
    if (callback) {
        const std::unique_ptr<springai::Game> game(callback->GetGame());
        if (game) {
            game->SendTextMessage("/say Data collection DISABLED", 0);
        }
    }
}

// Save training data in binary format for efficient storage
void CChanRTS::SaveTrainingDataBinary() {
    if (trainingBuffer.empty()) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                game->SendTextMessage("/say No training data to save (buffer empty)", 0);
            }
        }
        return;
    }

    std::lock_guard<std::mutex> lock(trainingMutex);

    try {
        // Create filename with timestamp and game info
        auto now = std::chrono::system_clock::now();
        auto time_t = std::chrono::system_clock::to_time_t(now);
        
        std::string filename;
        if (!dataOutputDir.empty()) {
            filename = dataOutputDir + "/chanrts_training_" + std::to_string(time_t) + ".bin";
        } else {
            filename = "/tmp/chanrts_training_" + std::to_string(time_t) + ".bin";
        }
        
        std::ofstream file(filename, std::ios::binary);
        
        if (!file.is_open()) {
            throw std::runtime_error("Could not open file for writing: " + filename);
        }
        
        // Write binary format header
        uint32_t version = 1;
        uint32_t sampleCount = trainingBuffer.size();
        file.write(reinterpret_cast<const char*>(&version), sizeof(version));
        file.write(reinterpret_cast<const char*>(&sampleCount), sizeof(sampleCount));
        
        // Write each training sample
        for (const auto& sample : trainingBuffer) {
            // Sample metadata
            file.write(reinterpret_cast<const char*>(&sample.sampleFrame), sizeof(sample.sampleFrame));
            file.write(reinterpret_cast<const char*>(&sample.reward), sizeof(sample.reward));
            file.write(reinterpret_cast<const char*>(&sample.gameWon), sizeof(sample.gameWon));
            
            // Game state data
            file.write(reinterpret_cast<const char*>(&sample.state.currentFrame), sizeof(sample.state.currentFrame));
            file.write(reinterpret_cast<const char*>(&sample.state.gameProgress), sizeof(sample.state.gameProgress));
            file.write(reinterpret_cast<const char*>(&sample.state.mapWidth), sizeof(sample.state.mapWidth));
            file.write(reinterpret_cast<const char*>(&sample.state.mapHeight), sizeof(sample.state.mapHeight));
            
            // Resource data
            file.write(reinterpret_cast<const char*>(&sample.state.metal), sizeof(sample.state.metal));
            file.write(reinterpret_cast<const char*>(&sample.state.energy), sizeof(sample.state.energy));
            file.write(reinterpret_cast<const char*>(&sample.state.metalIncome), sizeof(sample.state.metalIncome));
            file.write(reinterpret_cast<const char*>(&sample.state.energyIncome), sizeof(sample.state.energyIncome));
            
            // Strategic data
            file.write(reinterpret_cast<const char*>(&sample.state.totalUnitCount), sizeof(sample.state.totalUnitCount));
            file.write(reinterpret_cast<const char*>(&sample.state.militaryUnitCount), sizeof(sample.state.militaryUnitCount));
            file.write(reinterpret_cast<const char*>(&sample.state.economicUnitCount), sizeof(sample.state.economicUnitCount));
            
            // Unit data
            uint32_t unitCount = sample.state.allUnits.size();
            file.write(reinterpret_cast<const char*>(&unitCount), sizeof(unitCount));
            
            for (const auto& unit : sample.state.allUnits) {
                file.write(reinterpret_cast<const char*>(&unit), sizeof(unit));
            }
            
            // Action data
            file.write(reinterpret_cast<const char*>(&sample.action.strategicState), sizeof(sample.action.strategicState));
            file.write(reinterpret_cast<const char*>(&sample.action.frame), sizeof(sample.action.frame));
            file.write(reinterpret_cast<const char*>(&sample.action.economicPriority), sizeof(sample.action.economicPriority));
            
            uint32_t actionCount = sample.action.unitActions.size();
            file.write(reinterpret_cast<const char*>(&actionCount), sizeof(actionCount));
            
            for (const auto& unitAction : sample.action.unitActions) {
                file.write(reinterpret_cast<const char*>(&unitAction), sizeof(unitAction));
            }
        }
        
        file.close();
        
        // Send confirmation
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string msg = "/say Binary training data saved: " + filename + 
                                " (" + std::to_string(trainingBuffer.size()) + " samples)";
                game->SendTextMessage(msg.c_str(), 0);
            }
        }
        
    } catch (const std::exception& e) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = "/say Binary save error: " + std::string(e.what());
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Process replay files for training data extraction
void CChanRTS::ProcessReplay(const std::string& replayPath, const std::string& outputDir) {
    // This method is intended to be called by external replay processing tools
    // The actual replay processing is handled by the Spring engine itself
    // When ChanRTS runs in replay mode, it automatically collects training data
    
    if (callback) {
        const std::unique_ptr<springai::Game> game(callback->GetGame());
        if (game) {
            std::string msg = "/say Processing replay: " + replayPath + " -> " + outputDir;
            game->SendTextMessage(msg.c_str(), 0);
        }
    }
    
    // Enable data collection for replay processing
    EnableDataCollection(outputDir, true);
    
    // Set collection parameters for replay mode (more frequent collection)
    std::lock_guard<std::mutex> lock(trainingMutex);
    // In replay mode, we want more training samples
    // The actual game loop will handle collection at the specified intervals
}

// Check environment variables and configuration for data collection settings
void CChanRTS::CheckDataCollectionConfig() {
    try {
        // Check for CHANRTS_CONFIG_PATH environment variable
        const char* configPath = std::getenv("CHANRTS_CONFIG_PATH");
        if (configPath) {
            LoadConfigFromFile(std::string(configPath));
            return;
        }
        
        // Check individual environment variables
        const char* enableCollection = std::getenv("CHANRTS_COLLECT_DATA");
        const char* outputDirEnv = std::getenv("CHANRTS_OUTPUT_DIR");
        const char* replayModeEnv = std::getenv("CHANRTS_REPLAY_MODE");
        const char* playerSkillEnv = std::getenv("CHANRTS_PLAYER_SKILL");
        const char* gameIdEnv = std::getenv("CHANRTS_GAME_ID");
        
        if (enableCollection && std::string(enableCollection) == "1") {
            collectTrainingData = true;
            
            if (outputDirEnv) {
                dataOutputDir = std::string(outputDirEnv);
            }
            
            if (replayModeEnv && std::string(replayModeEnv) == "1") {
                replayMode = true;
            }
            
            if (playerSkillEnv) {
                playerSkill = std::stof(std::string(playerSkillEnv));
            }
            
            if (gameIdEnv) {
                gameId = std::stoi(std::string(gameIdEnv));
            }
        }
        
    } catch (const std::exception& e) {
        // Log error but continue
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string errorMsg = "/say Config load error: " + std::string(e.what());
                game->SendTextMessage(errorMsg.c_str(), 0);
            }
        }
    }
}

// Load configuration from JSON file
void CChanRTS::LoadConfigFromFile(const std::string& configPath) {
    std::ifstream configFile(configPath);
    if (!configFile.is_open()) {
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string msg = "/say Could not open config file: " + configPath;
                game->SendTextMessage(msg.c_str(), 0);
            }
        }
        return;
    }
    
    // Read entire file into string
    std::string configContent((std::istreambuf_iterator<char>(configFile)),
                              std::istreambuf_iterator<char>());
    configFile.close();
    
    // Simple JSON parsing for data collection configuration
    // This is a simplified parser - for production you'd want a proper JSON library
    if (configContent.find("\"enabled\": true") != std::string::npos) {
        collectTrainingData = true;
        
        // Extract output directory
        size_t outputDirPos = configContent.find("\"output_directory\":");
        if (outputDirPos != std::string::npos) {
            size_t startQuote = configContent.find("\"", outputDirPos + 18);
            size_t endQuote = configContent.find("\"", startQuote + 1);
            if (startQuote != std::string::npos && endQuote != std::string::npos) {
                dataOutputDir = configContent.substr(startQuote + 1, endQuote - startQuote - 1);
            }
        }
        
        // Extract player skill
        size_t skillPos = configContent.find("\"player_skill_estimate\":");
        if (skillPos != std::string::npos) {
            size_t valueStart = configContent.find_first_of("0123456789.", skillPos);
            if (valueStart != std::string::npos) {
                size_t valueEnd = configContent.find_first_of(",}", valueStart);
                if (valueEnd != std::string::npos) {
                    std::string skillStr = configContent.substr(valueStart, valueEnd - valueStart);
                    playerSkill = std::stof(skillStr);
                }
            }
        }
        
        // Extract replay mode
        if (configContent.find("\"replay_mode\": true") != std::string::npos) {
            replayMode = true;
        }
        
        if (callback) {
            const std::unique_ptr<springai::Game> game(callback->GetGame());
            if (game) {
                std::string msg = "/say Loaded config from: " + configPath;
                game->SendTextMessage(msg.c_str(), 0);
            }
        }
    }
}

} // namespace chanrts
